package com.barcode.zxing;

import com.google.zxing.*;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;

public class ReadBarCode {
    public static void main(String args[]) throws IOException, NotFoundException {
        MultiFormatReader formatReader = new MultiFormatReader();

        //this can read bar code generated by qrcode also
        File file = new File("/Users/wuwenyi1/Documents/Google Drive/Programming/JAVA/bar_code/src/lib/zxing.png");
        BufferedImage image = ImageIO.read(file);
        BinaryBitmap binaryBitmap = new BinaryBitmap(new HybridBinarizer(new BufferedImageLuminanceSource(image)));

        HashMap hints = new HashMap();
        hints.put(EncodeHintType.CHARACTER_SET, "utf-8");

        Result result = formatReader.decode(binaryBitmap, hints);

        System.out.println(result.toString());
        System.out.println(result.getBarcodeFormat());
        System.out.println(result.getText());
    }
}
