<%@ page contentType="text/html;charset=UTF-8" language="java" pageEncoding="UTF-8" %>
<html>
  <head>
    <title>generate bar code by jquery qrcode</title>

    <script type="text/javascript" src="jquery.min.js"></script>
    <script type="text/javascript" src="jquery.qrcode.min.js"></script>
  </head>
  <body>
    <div id="qrcode"></div>
    <script type="text/javascript">
        jQuery('#qrcode').qrcode("bar code generated by jquery qrcode");
    </script>
  </body>
</html>
